core/views.py
from flask import current_app, Blueprint, render_template, redirect, url_for, request, session

main_app = Blueprint('main_app', __name__, template_folder='templates')

@main_app.route('/')
def home():
    return render_template('home.html')

@main_app.route('/history')
def history():
    return render_template('history.html')

@main_app.route('/donate')
def donate():
    return render_template('donate.html')

@main_app.route('/project-aims')
def aims():
    return render_template('project-aims.html')

@main_app.route('/contact')
def contact():
    return render_template('contact.html')

@main_app.route('/ramadan-2019')
def ramadan_2019():
    return render_template('/ramadan-2019.html')

@main_app.route('/ramadan-appeal-2020')
def ramadan_appeal_2020():
    return render_template('/ramadan-appeal-2020.html')

@main_app.route('/bakrid-2019')
def bakrid_2019():
    return render_template('/bakrid-2019.html')

@main_app.route('/water-pump-2019')
def water_pump_2019():
    return render_template('/water-pump-2019.html')

@main_app.route('/masjid-2019')
def masjid_2019():
    return render_template('/mosque-2019.html')

@main_app.route('/masjid-jan-2021')
def masjid_jan_2021():
    return render_template('/mosque-jan-2021.html')

@main_app.route('/water-pump-jan-2021')
def water_pump_jan_2021():
    return render_template('water-pump-jan-2021.html')

@main_app.route('/madrasah-2020')
def madrasah_2020():
    return render_template('/madrasah-2020.html')

@main_app.route('/update-nov-2021')
def update_nov_2021():
    return render_template('/update-nov-21.html')

@main_app.route('/update-mar-2023')
def update_mar_2023():
    return render_template('/update-mar-23.html')

@main_app.route('/accreditation')
def accreditation():
    return render_template('accreditation.html')

core/templates/bakrid-2019.html
{% extends "base.html" %}
{% block title %} Eid-ul Adha 2019 {% endblock title %}

{% block head %}
{{ super() }}
{% endblock head %}

{# body begins #}
{% block content %}

<main>
    <div style="padding-left: 3rem;">
        <div class="columns">
            <div class="column is-12">
                <div class="content is-medium">
                    <p class="title is-3 is-spaced">Eid-ul Adha 2019</p>
                    <p></p>
                    <p>
                        Alhamdulillah, thanks to the many generous individual and group donations, we were 
                        able to perform the qurbani and deliver the meat to the refugees in the camp. In total, we slaughtered 15 cows, 9 sheep and a goat that were used to feed 1800 families. In addition, we provided hot meals to 450 orphan children. We also distributed 190 Quran mushaf for the refugees.
                    </p>

                    <div id="gallery" style="display:none; margin: 0px auto;">

                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-1.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-1.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-2.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-2.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-3.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-3.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-4.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-4.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-5.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-5.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-6.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-6.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-7.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-7.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-8.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-8.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-9.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-9.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-10.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-10.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-11.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-11.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-12.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-12.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-13.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-13.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-14.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-14.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-15.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-15.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-16.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-16.jpg' )}}"
                            data-description="Eid ul Adha 2019">
                            <img alt="" src="{{ url_for( 'static', filename='images/media/bakrid2019/b19-17.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/bakrid2019/b19-17.jpg' )}}"
                            data-description="Eid ul Adha 2019">

                            <img alt="Books Distribution" data-type="youtube" data-videoid="THLhUWxYuvc" data-description="Books Distribution">
                            <img alt="Books Distribution" data-type="youtube" data-videoid="I5pPt4mnFUo" data-description="Books Distribution">
                            <img alt="Meals for Orphans" data-type="youtube" data-videoid="80SuqtzNDoo" data-description="Eid ul Adha Meals">
                            <img alt="Books Distribution" data-type="youtube" data-videoid="9Q8JSOaHQuA" data-description="Books Distribution">
                            <img alt="Books Distribution" data-type="youtube" data-videoid="VF8iAvk5kb8" data-description="Books Distribution">
                    </div>
                    <br />
                    <p>We are extremely thankful for the supporters and the donors of UDES. This initiative cannot succeed without your support. May Allah reward you abundantly. If you need any further information or would like to support us, please do not hesitate to <a href="{{url_for('main_app.contact')}}">contact us</a>.</p>
                </div>
            </div>
        </div>
    </div>
</main>

<script type="text/javascript">
    // A $( document ).ready() block.

    $(document).ready(function () {
        $("#gallery").unitegallery({
            gallery_autoplay: true,
            gallery_play_interval: 5000,
            theme_enable_text_panel: true,
            slider_scale_mode: 'down'
        });
    });

</script>

{% endblock content %}

{% block footer %}
{{ super() }}
{% endblock %}

core/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name='viewport' content="width=device-width, initial-scale=1">
    <link rel="icon" href="{{ url_for( 'static', filename='images/favicon.ico' )}}" type="image/x-icon" />

    {% block head %}
    <title>UDES - {% block title %}{% endblock %}</title>
    <!-- CSS tags -->
    {#
    <link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/base.css' )}}" />
    #}
    {% assets filters="cssmin", output="gen/packed.css",
    "css/styles.css",
    "css/base.css",
    "node_modules/unitegallery/dist/css/unite-gallery.css",
    "node_modules/unitegallery/dist/themes/default/ug-theme-default.css"
    %}
    <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
    {% endassets %}

    <!-- Script tags -->
    {% assets filters="jsmin", output="gen/packed.js",
    "node_modules/jquery/dist/jquery.min.js",
    "node_modules/unitegallery/dist/js/unitegallery.min.js",
    "node_modules/unitegallery/dist/themes/default/ug-theme-default.js"
    %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}

    {{ JSGlue.include()}}

    {% endblock %}
</head>

<body>

    {% block header %}
    <nav class="navbar has-shadow is-spaced" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{{url_for('main_app.home')}}">
                <img src="{{ url_for( 'static', filename='images/udes-text-icon.png' )}}" style="max-height: 2.8rem;">
            </a>



            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="{{url_for('main_app.home')}}">
                    Home
                </a>

                <a class="navbar-item" href="{{url_for('main_app.history')}}">
                    History
                </a>
                <a class="navbar-item" href="{{url_for('main_app.aims')}}">
                    Charity Aims
                </a>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                      Projects
                    </a>
            
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{{url_for('main_app.update_mar_2023')}}">
                            Update - Mar 2023
                        </a>
                        <a class="navbar-item" href="{{url_for('main_app.update_nov_2021')}}">
                            Update - Nov 2021
                        </a>
                        <a class="navbar-item" href="{{url_for('main_app.masjid_jan_2021')}}">
                            Masjid Development 2021
                        </a>
                        <a class="navbar-item" href="{{url_for('main_app.water_pump_jan_2021')}}">
                            Water Pumps 2021
                        </a>
                        <a class="navbar-item" href="{{url_for('main_app.madrasah_2020')}}">
                            Madrasah Development 2020
                        </a>
                        <a class="navbar-item" href="{{url_for('main_app.ramadan_2019')}}">
                            Ramadan 2019
                        </a>
                        <a class="navbar-item" href="{{url_for('main_app.bakrid_2019')}}">
                            Bakrid 2019
                        </a>
                        <a class="navbar-item" href="{{url_for('main_app.water_pump_2019')}}">
                            Water Pump
                        </a>
                        <a class="navbar-item" href="{{url_for('main_app.masjid_2019')}}">
                            Masjid Construction
                        </a>
                    </div>
                </div>
                <!--
                <a class="navbar-item" href="{{url_for('main_app.ramadan_appeal_2020')}}">
                    Ramadan Appeal 2020
                </a>
                -->
                <a class="navbar-item" href="{{url_for('main_app.contact')}}">
                    Contact Us
                </a>

            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary" href="{{url_for('main_app.donate')}}">
                            <strong>Donate</strong>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    {% endblock %}

    {% block content %}{% endblock %}

    {% block footer %}
    <footer class="footer" style="margin-top: 1rem; color: #deb887;">
        <div class="columns">
            <div class="column is-9">
                <div class="content">
                    <p>
                        UDES is registered with Charity Commission For England and Wales. Reg no: 1192261
                    </p>
                </div>
            </div>
            <div class="column is-3">
                <div class="content">
                    <p><span style="font-weight: bold;">Contact Us</span><br />
                        Email: contact@udes.co.uk<br />
                        UK Phone: +44 7541 992 350<br />
                        Cameroon Phone: +237 6953 64834
                    </p>
                </div>
            </div>
        </div>
        <div class="content" style="color: #6f5e48;">

            <p>
                <span>© Copyright 2018-Present</span>
                <span style="float: right;"><a style="color: #6f5e48;" href="{{url_for('main_app.accreditation')}}">Accreditation</a></span>
            </p>
        </div>

    </footer>
    {% endblock %}

</body>

<script type="text/javascript">
    $(document).ready(function () {

        // Check for click events on the navbar burger icon
        $(".navbar-burger").click(function () {

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            $(".navbar-burger").toggleClass("is-active");
            $(".navbar-menu").toggleClass("is-active");

        });
    });
</script>

</html>

core/templates/donate.html
{% extends "base.html" %}
{% block title %} Donate {% endblock title %}

{% block head %}
{{ super() }}
{% endblock head %}

{# body begins #}
{% block content %}

<main>
    <div style="padding-left: 3rem;">
        <div class="columns">
            <div class="column is-12">
                <div class="content is-medium">
                    <p class="title is-3 is-spaced">Donate</p>
                    <p>You can make a bank transfer to our UK bank account. The information is provided below.
                        If you have any questions, you can find our contact information from <a href="{{url_for('main_app.contact')}}">Contact
                            Us</a> page.
                        <br />
                    </p>
                    <p>
                        <strong>Bank name: </strong>COOPERATIVE BANK<br/>
                        <strong>Charity name: </strong>UNIVERSAL DEVELOPMENT and EDUCATION SOLIDARITY<br/>
                        <strong>Sort Code: </strong>08-92-99<br/>
                        <strong>Account Number: </strong>67217933<br/>
                    </p>
                </div>
            </div>
        </div>
        <!-- <div class="columns">
            <div class="column">
                <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSemHYouRw9k1s7f3WAHcWY95W02DEHXKQtVxYX0blj_IciAGQ/viewform?embedded=true"
                    width="350" height="1347" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
            </div>
        </div> -->
    </div>
</main>

{% endblock content %}

{% block footer %}
{{ super() }}
{% endblock %}

core/templates/home.html
{% extends "base.html" %}
{# The blocks written here will replace the blocks
in base.html. if super() is called, the block from
base.html will be inserted first and then
the new block will be replaced #}
{% block title %} Home {% endblock title %}

{% block head %}
{{ super() }}
{% endblock head %}

{# body begins #}
{% block content %}

<main>

    <div id="intro-screen">
        <div id="image-container" style="overflow: hidden">
            <img src="{{ url_for( 'static', filename='images/home-bg.jpg' )}}" class="home-background" />
        </div>

        <div id="content-container" style="position: absolute; top: 10rem;">
            <div class="columns">
                <div class="column"></div>
            </div>
            <div class="columns">
                <div class="column"></div>
            </div>
            <div class="columns">
                <div class="column"></div>
            </div>
            <div class="columns">
                <div class="column is-7 is-offset-3" style="border: 3px white solid;">
                    <p style="color: white;font-size: 4rem;text-align: center;">
                        Universal Development and Education Solidarity
                    </p>
                </div>
            </div>
            <div class="columns">
                <div class="column"></div>
            </div>

            <div class="columns">
                <div class="column is-7 is-offset-3">
                    <p style="color: white;font-size: 1.5rem;text-align: center;">
                        UDES is a charity working to help refugees fleeing persecution in Central African Republic.</p>
                </div>
            </div>
        </div>
    </div>
    <div id="map-screen" style="padding-left: 1rem;">
        <div class="columns">
            <div class="column"></div>
        </div>
        <div class="columns">
            <div class="column is-6" style="background-color: #209cee; color: #fff;">
                <h2 class="title is-2" style="color: #fff;">Refugee Camps in Cameroon</h2>
                <div class="content is-medium">
                    <p>
                        The Borgop village houses one of the three UN-run camps for the refugees from CAR.
                        It accomodates nearly 14,000 people including women, elderly men and children, many
                        of whom are orphans. The village is located at a distance of about 35 miles from the town of
                        Meiganga (shown in the map).
                        <br /><br />
                        The largest of these camps is in Garoua-Boulay with nearly 80,000 refugees and another in Gam
                        with about 6,000 refugees.
                        <br /><br />
                        Refugees live in poor conditions and are in dire need of support in terms of food, clothing,
                        education and potentially sustainable economic means.
                        <br /><br />
                        To learn more about the history and what we are doing to help, <a style="color: #0f3a7d;text-decoration: underline;"
                            href="{{url_for('main_app.history')}}">click here</a> or <a style="color: #0f3a7d; text-decoration: underline;"
                            href="{{url_for('main_app.donate')}}">donate now</a>.</p>
                </div>
            </div>
            <div class="column is-6">
                <!--Map embed-->
                <div class="mapouter">
                    <div class="gmap_canvas">
                        <iframe id="gmap_canvas" src="https://maps.google.com/maps?q=meiganga%20cameroon&t=&z=5&ie=UTF8&iwloc=&output=embed"
                            frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
                        </iframe>
                    </div>
                </div>
                <!--Map embed close-->
            </div>

        </div>
    </div>
    <div id="icons-screen" style="padding-left: 1rem;">
        <div class="columns">
            <div class="column"></div>
        </div>
        <div class="columns">
            <div class="column is-6 is-offset-3">
                <h2 class="title is-4">What we have managed to provide so far...</h2>
            </div>
        </div>
        <div class="columns">
            <div class="column is-5 is-offset-1">
                <div class="box">
                    <article class="media">
                        <div class="media-left">
                            <figure class="image is-96x96">
                                <img src="{{ url_for( 'static', filename='images/icons/food.svg' )}}" alt="Image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <strong>Food</strong>
                                    <br>
                                    During the month of Ramadan we visited the camp to provide them meat, dairy and
                                    other perishable and non-perishable food items.
                                </p>
                            </div>
                    </article>
                </div>
            </div>
            <div class="column is-5">
                <div class="box">
                    <article class="media">
                        <div class="media-left">
                            <figure class="image is-96x96">
                                <img src="{{ url_for( 'static', filename='images/icons/clothes.svg' )}}" alt="Image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <strong>Clothing</strong>
                                    <br>
                                    We provided clothes that were collected from generous donors and also had the
                                    opportunity to provide some of the orphans with new clothes for Eid.
                                </p>
                            </div>
                    </article>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column is-5 is-offset-1">
                <div class="box">
                    <article class="media">
                        <div class="media-left">
                            <figure class="image is-96x96">
                                <img src="{{ url_for( 'static', filename='images/icons/mosque.svg' )}}" alt="Image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <strong>Religious needs</strong>
                                    <br>
                                    We helped build a Masjid so that the refugees can perform their five daily prayers.
                                    A Madrasah for both girls and boys with paid teachers was also established.
                                </p>
                            </div>
                    </article>
                </div>
            </div>
            <div class="column is-5">
                <div class="box">
                    <article class="media">
                        <div class="media-left">
                            <figure class="image is-96x96">
                                <img src="{{ url_for( 'static', filename='images/icons/support.svg' )}}" alt="Image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <strong>Support</strong>
                                    <br>
                                    We try as much as possible to give the care each of them need. We did help some
                                    families to build a basic source of income, and we intend to support a few more.
                                </p>
                            </div>
                    </article>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column"></div>
        </div>
        <!-- <div class="columns">
            <div class="column is-12">
                <div id="gallery" style="display:none; margin: 0px auto;">

                    <img alt="" src="{{ url_for( 'static', filename='images/home-bg.jpg' )}}" data-image="{{ url_for( 'static', filename='images/home-bg.jpg' )}}"
                        data-description="">
                    <img alt="" src="{{ url_for( 'static', filename='images/media/2.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/2.jpg' )}}"
                        data-description="">
                    <img alt="" src="{{ url_for( 'static', filename='images/media/3.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/3.jpg' )}}"
                        data-description="">
                    <img alt="" src="{{ url_for( 'static', filename='images/media/5.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/5.jpg' )}}"
                        data-description="">
                    <img alt="" src="{{ url_for( 'static', filename='images/media/8.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/8.jpg' )}}"
                        data-description="">
                    <img alt="" src="{{ url_for( 'static', filename='images/media/9.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/9.jpg' )}}"
                        data-description="">
                    <img alt="" src="{{ url_for( 'static', filename='images/media/10.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/10.jpg' )}}"
                        data-description="">
                    <img alt="" src="{{ url_for( 'static', filename='images/media/15.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/15.jpg' )}}"
                        data-description="">
                    <img alt="" src="{{ url_for( 'static', filename='images/media/14.jpg' )}}" data-image="{{ url_for( 'static', filename='images/media/14.jpg' )}}"
                        data-description="">

                </div>
            </div>
        </div> -->
        <div class="columns notification is-primary">
            
            <div class="column is-12">
                <div class="content is-medium" style="font-weight:bold;">
                    It was narrated that Abu Hurayrah (may Allaah be pleased with him) said: The Messenger of Allaah
                    (peace and blessings of Allaah be upon him) said: “Whoever gives charity equal to a date from good
                    (halal) earnings – for Allaah does not accept anything but that which is good – Allaah will take it
                    in His right hand and tend it for the one who gave it as any one of you tends his foal, until it
                    becomes like a mountain.”
                    <br>
                    Narrated by al-Bukhaari, 1344; Muslim, 1014.
                </div>
                <!-- <div class="content">
                    We are very grateful to the excellent support provided by the charity <a target="_blank" href="https://www2.caravanofmercy.org/2017/08/09/by-car-to-car-refugees/">Caravan
                        of Mercy</a> (Leicester,
                    UK) and their generous donors. We have a long way to go in our efforts and we sincerely ask you to
                    support us with your sadaqah, zakah or general donations.
                </div> -->
            </div>
        </div>
        <br /></br />
        <div class="columns">
            <div class="column is-offset-5">
                <div class="buttons">
                    <a class="button is-outlined is-success is-medium" href="{{url_for('main_app.donate')}}">
                        Click to Donate now
                    </a>
                </div>
            </div>
        </div>
        <br />
    </div>

</main>
<script type="text/javascript">
    // A $( document ).ready() block.

    $(document).ready(function () {
        $("#gallery").unitegallery({
            gallery_autoplay: true,
            gallery_play_interval: 5000,
            theme_enable_text_panel: false,
            slider_scale_mode: 'down',
            gallery_width: 1100,
            gallery_height: 610
        });
    });

</script>


{% endblock content %}

{% block footer %}
{{ super() }}
{% endblock %}